
export __HOME_ZSHRC_SOURCED=$(( ${__HOME_ZSHRC_SOURCED:-0} + 1 ))

export PATH="$PATH:$HOME/.local/bin"

# XDG
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_DIRS="$XDG_DATA_DIRS:$XDG_DATA_HOME"

for f in "$XDG_CONFIG_HOME/zsh/rc.d/"*.zsh; do
    source "$f"
done

